### ISSUE TITLE
Where do you put the downloaded hgt files ?

### ISSUE THREAD

**Issue by ABelliqueux** [BourgeoisLab/GPXLab#10]
Hi, 

Just discovering your software and trying to add elevation data to a gpx file.
The dialog gives me a download error and provide me with a link. 

Where should I put the resulting hgt file ?

I tried ~/.cache/BourgeoisLab/ and ~/.config/BourgeoisLab with no luck. I checked the code for a clue but no luck there either. Can you shed a light please ?

Other than that, this looks very useful for my purpose, thanks for your work !

**Comment by BourgeoisLab** [comment]
Hello

You have to unzip the hgt file first. Then put the file in the same location as the executable. Although I'm not 100% sure if it works under Linux. I will make a change, so that it will look in different locations and show a notice that the file should be unpacked first.

**Comment by ABelliqueux** [comment]
Hi, 

Thanks for your answer. Sadly it doesn't seem to work after unzipping the file in the executable directory (/usr/bin).
Plus, it seems impractical and unsecure to do it that way on linux, since you need root permissions to write in /usr/bin/.

As you said, it would be better if it looked for the file in an other location, such as ~/.config/BourgeoisLab

FYI, I'm using the package from AUR in Manjaro Linux : https://aur.archlinux.org/packages/gpxlab/
If can try building from git and give you a feedback on your commits if you decide to dedicate some time to this matter. (Had I had the skills I would gladly have done it ..)

**Comment by BourgeoisLab** [comment]
I made the changes. Now the files must be stored in the .config directory. Matter of fact the file was searched in the working directory. Guess I haven't given much thoughts about it when implementing.

I am not the maintainer of the archlinux package, so you'll have to compile it yourself.

Please give a feedback if it worked (or nor).

**Comment by sikmir** [comment]
I've updated AUR package.

**Comment by sikmir** [comment]
Actually. `~/.config` (`QStandardPaths::AppConfigLocation`) directory is not a proper place for HGT files, it should be `~/.local/share` (`QStandardPaths::AppDataLocation`). See [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for more details.

**Comment by ABelliqueux** [comment]
Hi !

Thanks to you both, I was able to build from AUR and can confirm it now works fine, although the elevation values seem quite aberrant. For instance at some points, I get a high elevation on the beach... 

For example, a point with coordinates 47.591250, -2.721889 ( 47°35'28.5"N 2°43'18.8"W ) gets a 32 meters elevation. Checking the same location in https://www.calcmaps.com/map-elevation/ gives an elevation of 1 meter, which is much more close to reality.

I'll duplicate the second part of this message in a new issue, so feel free to close this one as solved !

Thanks again for your time and work.
