### ISSUE TITLE
Combine Track Issue?

### ISSUE THREAD

**Issue by ShelleyLake** [BourgeoisLab/GPXLab#26]
From what I can understand "Combine Track" fuses two consecutive tracks at the selected point.
In my case the selected point is the last one of the first track AND the first one of the second track: as result, the point is repeated twice in the final track.

- Question: Wouldn't it be logical if the point were repeated only once?

Thanks.

![grafik](https://user-images.githubusercontent.com/49189962/70925822-36e74f00-202c-11ea-8de0-c0b9c7fa8118.png)

**Comment by sikmir** [comment]
It's not so easy to say if 2 points are equal (nearly equal). It's a matter of accuracy (time, lon, lat, ele).

**Comment by BourgeoisLab** [comment]
> 
> 
> It's not so easy to say if 2 points are equal (nearly equal). It's a matter of accuracy (time, lon, lat, ele).

That's right. Also depending on the application say 1m difference between the two points can be significant and in other application insignificant.

I would propose to remove the second point only if they are exactly the same.

**note for the implementation:** need to consider the undo/redo of this

**Comment by ShelleyLake** [comment]
I see in the code that a custom xml parser is used.
I thought the qt DOM XML or other library (like pugixml) was used, so that it's easy to check if two XML nodes are identical. Nevermind.
