### ISSUE TITLE
Enhancement - Change coordinates of a <trkpt> with drang'n'drop or mouse click

### ISSUE THREAD

**Issue by ShelleyLake** [BourgeoisLab/GPXLab#28]
Would it be possible to move a point (trkpt) by drag and drop of the green circle, or, I don't know, by activating a function from the context menu that "moves" the point where you click with the mouse?

**Comment by BourgeoisLab** [comment]
You can shift-leftclick on the map to move the selected point.
Unfortunately it doesn't support "dragging" the point, which would be much nicer.

**Comment by ShelleyLake** [comment]
Well, your hint was very helpful. What I needed. Thanks.
